Player:
	Name: Moogle Express
	Color: 133,163,220

Game:
	Mod: ra
	ShowShellmap: False
	ViewportEdgeScrollStep: 39.56522
	AlwaysShowStatusBars: True
	TeamHealthColors: True
	NewsFetchedDate: 2015-10-01 00-00-00

Sound:
	MusicVolume: 0

Graphics:

Server:
	DiscoverNatDevices: True
	AllowPortForward: False

Debug:
	PerfText: True
	PerfGraph: True

Keys:

